In [5]:
import pandas as pd

# Read the CSV file

import pandas as pd

df = pd.read_csv("data/raw/airnb.csv")

df.head()

,Title,Detail,Date,Price(in dollar),Offer price(in dollar),Review and rating,Number of bed
0,"Chalet in Skykomish, Washington, US",Sky Haus - A-Frame Cabin,Jun 11 - 16,306.00,229.00,4.85 (531),4 beds
1,"Cabin in Hancock, New York, US",The Catskill A-Frame - Mid-Century Modern Cabin,Jun 6 - 11,485.00,170.00,4.77 (146),4 beds
2,"Cabin in West Farmington, Ohio, US",The Triangle: A-Frame Cabin for your city retreat,Jul 9 - 14,119.00,522.00,4.91 (515),4 beds
3,"Home in Blue Ridge, Georgia, US",*Summer Sizzle* 5 Min to Blue Ridge* Pets* Hot...,Jun 11 - 16,192.00,348.00,4.94 (88),5 beds
4,"Treehouse in Grandview, Texas, US",Luxury Treehouse Couples Getaway w/ Peaceful V...,Jun 4 - 9,232.00,196.00,4.99 (222),1 queen bed

In [8]:
df.info()
df.describe(include="all")

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 953 entries, 0 to 952
Data columns (total 7 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Title                   953 non-null    object
 1   Detail                  953 non-null    object
 2   Date                    953 non-null    object
 3   Price(in dollar)        953 non-null    object
 4   Offer price(in dollar)  166 non-null    object
 5   Review and rating       947 non-null    object
 6   Number of bed           953 non-null    object
dtypes: object(7)
memory usage: 52.2+ KB

,Title,Detail,Date,Price(in dollar),Offer price(in dollar),Review and rating,Number of bed
count,953,953,953,953,166,947,953
unique,756,839,204,322,108,754,33
top,"Apartment in Kuala Lumpur, Malaysia",Cozy room 48.5 sq.m @The Astra near Night market,May 1 - 6,111.00,66.00,New,2 beds
freq,7,3,219,13,4,16,221

In [12]:
df.detail = (
    df.detail
    .str.strip()
    .str.lower()
    .str.replace(" ", "_", regex=False)
    .str.replace("/", "_", regex=False)
    .str.replace("*", "_", regex=False)    
    .str.replace(r"[^a-z0-9_]", "", regex=True)
)
display (df)

,title,detail,date,pricein_dollar,offer_pricein_dollar,review_and_rating,number_of_bed
0,"Chalet in Skykomish, Washington, US",sky_haus__aframe_cabin,Jun 11 - 16,306.00,229.00,4.85 (531),4 beds
1,"Cabin in Hancock, New York, US",the_catskill_aframe__midcentury_modern_cabin,Jun 6 - 11,485.00,170.00,4.77 (146),4 beds
2,"Cabin in West Farmington, Ohio, US",the_triangle_aframe_cabin_for_your_city_retreat,Jul 9 - 14,119.00,522.00,4.91 (515),4 beds
3,"Home in Blue Ridge, Georgia, US",_summer_sizzle__5_min_to_blue_ridge__pets__hot...,Jun 11 - 16,192.00,348.00,4.94 (88),5 beds
4,"Treehouse in Grandview, Texas, US",luxury_treehouse_couples_getaway_w__peaceful_v...,Jun 4 - 9,232.00,196.00,4.99 (222),1 queen bed
...,...,...,...,...,...,...,...
948,Guest suite in Lake Worth,the_garden_suite_at_the_historic_chateau_bleu,May 1 - 6,141.00,NaN,4.85 (82),1 king bed
949,Room in Kissimmee,private_room_in_orlando_kissimmee_2twins_t1,May 1 - 6,43.00,NaN,4.9 (300),1 king bed
950,Guesthouse in San Antonio,casa_alexander,May 1 - 6,73.00,NaN,4.92 (282),5 beds
951,Apartment in Englewood,beach_front_unit_w__pool_sandy_toes__5,May 7 - 12,233.00,NaN,4.96 (318),4 beds
952,Room in Long Beach,across_the_street_from_beach_getaway_near_conv...,May 1 - 6,106.00,NaN,4.85 (97),4 beds

In [7]:
df["Date"].head(20)

0        Jun 11 - 16
1         Jun 6 - 11
2         Jul 9 - 14
3        Jun 11 - 16
4          Jun 4 - 9
5        Jun 21 - 26
6          Jun 4 - 9
7         Jun 8 - 15
8          Jul 3 - 8
9     Jun 26 - Jul 1
10        Sep 4 - 10
11         Jun 1 - 6
12         Jun 1 - 6
13       Sep 11 - 16
14         Jun 1 - 6
15        Sep 8 - 13
16       Jun 11 - 16
17       Jun 18 - 23
18       Aug 20 - 25
19        Jun 9 - 14
Name: Date, dtype: object